import { AdPackage, Ad, User, EnergyType, CreditBundle, Post } from './types';

export const APP_NAME = "Aura";
export const PRIMARY_COLOR = "emerald-600";

export const CREDIT_BUNDLES: CreditBundle[] = []; // Removed all credit bundles

export const INDUSTRIES = [
  'Technology & Software',
  'Healthcare',
  'Finance',
  'Education',
  'Marketing & Advertising',
  'Manufacturing',
  'Real Estate',
  'Retail',
  'Consulting',
  'Legal Services',
  'Non-Profit',
  'Government',
  'Energy',
  'Transportation',
  'Other'
];

export const COUNTRIES = [
  'United States',
  'United Kingdom',
  'Canada',
  'Australia',
  'Germany',
  'France',
  'Japan',
  'Singapore',
  'India',
  'Brazil',
  'South Africa',
  'Netherlands',
  'Sweden',
  'Other'
];

export const MOCK_USERS: User[] = [
  {
    id: '1',
    firstName: 'James',
    lastName: 'Mitchell',
    name: 'James Mitchell',
    handle: '@jamesmitchell',
    avatar: 'https://picsum.photos/id/64/150/150',
    acquaintances: ['2', '3', '4', '6', '7', '8', '9', '10', '11', '12'],
    email: 'james@leadership.io',
    dob: '1985-03-15',
    blockedUsers: [],
    trustScore: 98,
    auraCredits: 0,
    activeGlow: 'emerald',
    bio: 'CEO at Global Leadership Institute. Author of "The Adaptive Leader". Helping executives navigate complexity.',
    zodiacSign: 'Pisces ♓'
  },
  {
    id: '2',
    firstName: 'Sarah',
    lastName: 'Williams',
    name: 'Sarah Williams',
    handle: '@sarahwilliams',
    avatar: 'https://picsum.photos/id/65/150/150',
    acquaintances: ['1', '3', '5', '9', '11', '13', '14', '15'],
    email: 'sarah@careergrowth.com',
    dob: '1988-07-22',
    blockedUsers: [],
    trustScore: 95,
    auraCredits: 0,
    activeGlow: 'none',
    bio: 'Executive Career Coach. 15+ years helping professionals unlock their potential. TEDx speaker.',
    zodiacSign: 'Cancer ♋'
  },
  {
    id: '3',
    firstName: 'Michael',
    lastName: 'Chen',
    name: 'Michael Chen',
    handle: '@michaelchen',
    avatar: 'https://picsum.photos/id/1012/150/150',
    acquaintances: ['1', '2', '4', '10', '12', '16', '17', '18'],
    email: 'michael@venture.com',
    dob: '1982-11-03',
    blockedUsers: [],
    trustScore: 94,
    auraCredits: 0,
    activeGlow: 'cyan',
    bio: 'Managing Partner at Horizon Ventures. Investing in future of work and sustainable tech.',
    zodiacSign: 'Scorpio ♏'
  },
  {
    id: '4',
    firstName: 'Emily',
    lastName: 'Rodriguez',
    name: 'Emily Rodriguez',
    handle: '@emilyrodriguez',
    avatar: 'https://picsum.photos/id/1027/150/150',
    acquaintances: ['1', '3', '6', '11', '19', '20', '21', '22'],
    email: 'emily@innovationlab.io',
    dob: '1990-01-12',
    blockedUsers: [],
    trustScore: 97,
    auraCredits: 0,
    activeGlow: 'amber',
    bio: 'Founder & CEO of Innovation Labs. Building AI solutions for enterprise transformation.',
    zodiacSign: 'Capricorn ♑'
  },
  {
    id: '5',
    firstName: 'David',
    lastName: 'Thompson',
    name: 'David Thompson',
    handle: '@davidthompson',
    avatar: 'https://picsum.photos/id/1005/150/150',
    acquaintances: ['2', '6', '12', '23', '24', '25', '26'],
    email: 'david@strategy.com',
    dob: '1987-06-30',
    blockedUsers: [],
    trustScore: 91,
    auraCredits: 0,
    activeGlow: 'none',
    bio: 'Business Strategy Consultant. Helping companies scale from startup to enterprise.',
    zodiacSign: 'Cancer ♋'
  },
  {
    id: '6',
    firstName: 'Dr. Lisa',
    lastName: 'Anderson',
    name: 'Dr. Lisa Anderson',
    handle: '@drlisaanderson',
    avatar: 'https://picsum.photos/id/1062/150/150',
    acquaintances: ['1', '4', '5', '13', '27', '28', '29', '30'],
    email: 'lisa@psychology.edu',
    dob: '1983-03-25',
    blockedUsers: [],
    trustScore: 99,
    auraCredits: 0,
    activeGlow: 'emerald',
    bio: 'Organizational Psychologist. Researching leadership effectiveness and team dynamics.',
    zodiacSign: 'Aries ♈'
  },
  {
    id: '7',
    firstName: 'Robert',
    lastName: 'Kim',
    name: 'Robert Kim',
    handle: '@robertkim',
    avatar: 'https://picsum.photos/id/1001/150/150',
    acquaintances: ['1', '8', '14', '31', '32', '33', '34'],
    email: 'robert@fintech.io',
    dob: '1984-02-14',
    blockedUsers: [],
    trustScore: 93,
    auraCredits: 0,
    activeGlow: 'none',
    bio: 'CFO at FinTech Solutions. Expert in financial strategy and business scaling.',
    zodiacSign: 'Aquarius ♒'
  },
  {
    id: '8',
    firstName: 'Jennifer',
    lastName: 'Martinez',
    name: 'Jennifer Martinez',
    handle: '@jennifermartinez',
    avatar: 'https://picsum.photos/id/1003/150/150',
    acquaintances: ['1', '7', '10', '35', '36', '37', '38'],
    email: 'jennifer@marketing.com',
    dob: '1986-09-12',
    blockedUsers: [],
    trustScore: 89,
    auraCredits: 0,
    activeGlow: 'cyan',
    bio: 'CMO at Growth Marketing Agency. Building brands that matter in digital age.',
    zodiacSign: 'Virgo ♍'
  },
  {
    id: '9',
    firstName: 'William',
    lastName: 'Taylor',
    name: 'William Taylor',
    handle: '@williamtaylor',
    avatar: 'https://picsum.photos/id/1025/150/150',
    acquaintances: ['1', '3', '8', '39', '40', '41', '42'],
    email: 'william@legal.com',
    dob: '1981-11-20',
    blockedUsers: [],
    trustScore: 96,
    auraCredits: 0,
    activeGlow: 'none',
    bio: 'Corporate Attorney. Specializing in M&A and corporate governance.',
    zodiacSign: 'Scorpio ♏'
  },
  {
    id: '10',
    firstName: 'Amanda',
    lastName: 'White',
    name: 'Amanda White',
    handle: '@amandawhite',
    avatar: 'https://picsum.photos/id/1005/150/150',
    acquaintances: ['2', '4', '6', '43', '44', '45', '46'],
    email: 'amanda@hr.com',
    dob: '1989-04-15',
    blockedUsers: [],
    trustScore: 92,
    auraCredits: 0,
    activeGlow: 'cyan',
    bio: 'VP of HR at TechCorp. Building inclusive workplaces and talent development programs.',
    zodiacSign: 'Aries ♈'
  },
  {
    id: '11',
    firstName: 'Christopher',
    lastName: 'Brown',
    name: 'Christopher Brown',
    handle: '@christopherbrown',
    avatar: 'https://picsum.photos/id/1006/150/150',
    acquaintances: ['1', '5', '7', '47', '48', '49', '50'],
    email: 'chris@manufacturing.io',
    dob: '1983-08-10',
    blockedUsers: [],
    trustScore: 88,
    auraCredits: 0,
    activeGlow: 'none',
    bio: 'Operations Director at Smart Manufacturing. Optimizing supply chains with IoT.',
    zodiacSign: 'Leo ♌'
  },
  {
    id: '12',
    firstName: 'Michelle',
    lastName: 'Davis',
    name: 'Michelle Davis',
    handle: '@michelledavis',
    avatar: 'https://picsum.photos/id/1007/150/150',
    acquaintances: ['1', '3', '8', '51', '52', '53', '54'],
    email: 'michelle@nonprofit.org',
    dob: '1985-12-05',
    blockedUsers: [],
    trustScore: 94,
    auraCredits: 0,
    activeGlow: 'emerald',
    bio: 'Executive Director at Global Impact Foundation. Leading social change initiatives.',
    zodiacSign: 'Sagittarius ♐'
  },
  {
    id: '13',
    firstName: 'Daniel',
    lastName: 'Miller',
    name: 'Daniel Miller',
    handle: '@danielmiller',
    avatar: 'https://picsum.photos/id/1008/150/150',
    acquaintances: ['2', '6', '9', '55', '56', '57', '58'],
    email: 'daniel@consulting.com',
    dob: '1982-05-18',
    blockedUsers: [],
    trustScore: 90,
    auraCredits: 0,
    activeGlow: 'none',
    bio: 'Senior Consultant at McKinsey. Strategy and transformation expert.',
    zodiacSign: 'Taurus ♉'
  },
  {
    id: '14',
    firstName: 'Jessica',
    lastName: 'Wilson',
    name: 'Jessica Wilson',
    handle: '@jessicawilson',
    avatar: 'https://picsum.photos/id/1009/150/150',
    acquaintances: ['2', '7', '10', '59', '60', '61', '62'],
    email: 'jessica@education.edu',
    dob: '1987-09-25',
    blockedUsers: [],
    trustScore: 95,
    auraCredits: 0,
    activeGlow: 'none',
    bio: 'Dean of Business School. Shaping future business leaders through innovation.',
    zodiacSign: 'Libra ♎'
  },
  {
    id: '15',
    firstName: 'Matthew',
    lastName: 'Moore',
    name: 'Matthew Moore',
    handle: '@matthewmoore',
    avatar: 'https://picsum.photos/id/1010/150/150',
    acquaintances: ['2', '5', '11', '63', '64', '65', '66'],
    email: 'matthew@startup.io',
    dob: '1990-02-28',
    blockedUsers: [],
    trustScore: 87,
    auraCredits: 0,
    activeGlow: 'cyan',
    bio: 'Serial Entrepreneur. 3 exits, currently building future of remote work.',
    zodiacSign: 'Pisces ♓'
  }
];

export const AD_PACKAGES: AdPackage[] = [
  {
    id: 'pkg-leader',
    name: 'Leadership Pulse',
    subtitle: 'Amplify your executive presence',
    durationDays: 30,
    price: '$299 for 30 Days',
    numericPrice: 299,
    adLimit: 3,
    idealFor: 'Executives, Business Leaders, Consultants.',
    features: ['3 Leadership Signals', '30-Day Executive Reach', 'Professional Network Targeting', 'Leadership Analytics'],
    gradient: 'from-blue-500 to-indigo-600'
  },
  {
    id: 'pkg-career',
    name: 'Career Growth',
    subtitle: 'Accelerate your professional journey',
    durationDays: 30,
    price: '$199 for 30 Days',
    numericPrice: 199,
    adLimit: 2,
    idealFor: 'Career Professionals, Job Seekers, Coaches.',
    features: ['2 Career Signals', '30-Day Professional Visibility', 'Industry-Specific Targeting', 'Career Analytics'],
    gradient: 'from-emerald-500 to-teal-600'
  },
  {
    id: 'pkg-business',
    name: 'Business Impact',
    subtitle: 'Maximum business visibility',
    durationDays: 30,
    price: '$499 for 30 Days',
    numericPrice: 499,
    adLimit: 5,
    idealFor: 'Business Owners, Entrepreneurs, B2B Services.',
    features: ['5 Business Signals', '30-Day Business Network', 'Industry Leader Targeting', 'Business Growth Analytics'],
    gradient: 'from-purple-500 to-pink-600'
  }
];

export const INITIAL_ADS: Ad[] = [
  {
    id: 'ad-leadership-summit',
    ownerId: '1',
    ownerName: 'James Mitchell',
    ownerAvatar: 'https://picsum.photos/id/64/150/150',
    headline: 'Global Leadership Summit 2025',
    description: 'Join 500+ executives for premier leadership conference. Keynotes, workshops, and networking.',
    mediaUrl: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?q=80&w=800&auto=format&fit=crop',
    ctaText: 'Register Now',
    ctaLink: '#',
    isSponsored: true,
    placement: 'feed',
    status: 'active',
    subscriptionTier: 'Leadership Pulse',
    reactions: { '🎯': 45, '💼': 28 }
  },
  {
    id: 'ad-career-coaching',
    ownerId: '2',
    ownerName: 'Sarah Williams',
    ownerAvatar: 'https://picsum.photos/id/65/150/150',
    headline: 'Executive Career Transformation',
    description: '1-on-1 coaching to help you reach your next career milestone. Limited spots available.',
    mediaUrl: 'https://images.unsplash.com/photo-1515378791036-0648a3e77b4a?q=80&w=800&auto=format&fit=crop',
    ctaText: 'Book Session',
    ctaLink: '#',
    isSponsored: true,
    placement: 'feed',
    status: 'active',
    subscriptionTier: 'Career Growth',
    reactions: { '🚀': 67, '💡': 34 }
  },
  {
    id: 'ad-venture-fund',
    ownerId: '3',
    ownerName: 'Michael Chen',
    ownerAvatar: 'https://picsum.photos/id/1012/150/150',
    headline: 'Horizon Ventures Fund IV',
    description: 'Now accepting pitches from AI, sustainability, and future of work startups. $100M fund.',
    mediaUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=800&auto=format&fit=crop',
    ctaText: 'Submit Pitch',
    ctaLink: '#',
    isSponsored: true,
    placement: 'feed',
    status: 'active',
    subscriptionTier: 'Business Impact',
    reactions: { '💰': 89, '🚀': 156 }
  },
  {
    id: 'ad-innovation-lab',
    ownerId: '4',
    ownerName: 'Emily Rodriguez',
    ownerAvatar: 'https://picsum.photos/id/1027/150/150',
    headline: 'AI Transformation Workshop',
    description: 'Learn how to implement AI in your enterprise. Hands-on workshop with real-world case studies.',
    mediaUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=800&auto=format&fit=crop',
    ctaText: 'Join Workshop',
    ctaLink: '#',
    isSponsored: true,
    placement: 'feed',
    status: 'active',
    subscriptionTier: 'Leadership Pulse',
    reactions: { '🤖': 78, '⚡': 45 }
  },
  {
    id: 'ad-strategy-consulting',
    ownerId: '5',
    ownerName: 'David Thompson',
    ownerAvatar: 'https://picsum.photos/id/1005/150/150',
    headline: 'Business Scaling Strategy',
    description: 'From startup to enterprise in 12 months. Proven framework for sustainable growth.',
    mediaUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=800&auto=format&fit=crop',
    ctaText: 'Learn More',
    ctaLink: '#',
    isSponsored: true,
    placement: 'feed',
    status: 'active',
    subscriptionTier: 'Business Impact',
    reactions: { '📈': 92, '💼': 67 }
  },
  {
    id: 'ad-leadership-book',
    ownerId: '6',
    ownerName: 'Dr. Lisa Anderson',
    ownerAvatar: 'https://picsum.photos/id/1062/150/150',
    headline: 'The Adaptive Leader - Bestseller',
    description: 'Discover the science behind effective leadership. Now available in audiobook format.',
    mediaUrl: 'https://images.unsplash.com/photo-1531482615713-7afd792de7d1?q=80&w=800&auto=format&fit=crop',
    ctaText: 'Get Book',
    ctaLink: '#',
    isSponsored: true,
    placement: 'feed',
    status: 'active',
    subscriptionTier: 'Career Growth',
    reactions: { '📚': 123, '🧠': 89 }
  }
];

export const CURRENT_USER = MOCK_USERS[0];

export const INITIAL_POSTS: Post[] = [
  {
    id: 'post-leadership-vision',
    author: MOCK_USERS[0],
    content: "The most effective leaders don't just manage change—they architect the future. Today's business landscape requires vision that transcends quarterly reports and embraces transformational thinking. 🎯\n\nWhat's your leadership vision for 2025?\n\n#Leadership #Strategy #Vision",
    energy: EnergyType.DEEP_DIVE,
    radiance: 567,
    timestamp: Date.now() - 1200000,
    reactions: { '🎯': 145, '💡': 89, '🚀': 67 },
    comments: [],
    isBoosted: true,
    userReactions: []
  },
  {
    id: 'post-career-growth',
    author: MOCK_USERS[1],
    content: "Just helped my 100th client land their dream role! The secret? It's not about polishing your resume—it's about understanding your unique value proposition and communicating it with confidence. 💪\n\nCareer transformation is possible when you align passion with purpose.\n\n#CareerGrowth #ProfessionalDevelopment #JobSearch",
    mediaUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=800&auto=format&fit=crop',
    mediaType: 'image',
    energy: EnergyType.HIGH_ENERGY,
    radiance: 234,
    timestamp: Date.now() - 3600000,
    reactions: { '🚀': 178, '💼': 89, '🎉': 45 },
    comments: [
      {
        id: 'c1',
        author: MOCK_USERS[0],
        text: "Incredible milestone, Sarah! Your approach to value proposition is game-changing.",
        timestamp: Date.now() - 1800000,
        reactions: { '🤝': 12 },
        userReactions: []
      }
    ],
    userReactions: ['🚀']
  },
  {
    id: 'post-venture-insights',
    author: MOCK_USERS[2],
    content: "VC observation: The most successful founders aren't those with the best ideas—they're those who execute relentlessly and adapt quickly. Ideas are cheap; execution is everything. 💡\n\nSeeing amazing pitches in sustainability space this quarter. The future is bright!\n\n#VentureCapital #Startups #Investment",
    energy: EnergyType.CALM,
    radiance: 189,
    timestamp: Date.now() - 5400000,
    reactions: { '💰': 156, '🚀': 89, '💡': 67 },
    comments: [],
    userReactions: []
  },
  {
    id: 'post-innovation-daily',
    author: MOCK_USERS[3],
    content: "Day 45 of our 100-day AI transformation challenge. The results? 40% increase in productivity, 60% reduction in manual processes, and a team that's actually excited about Monday mornings. 🤖⚡\n\nInnovation isn't about technology—it's about people.\n\n#AI #DigitalTransformation #Innovation",
    mediaUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=800&auto=format&fit=crop',
    mediaType: 'image',
    energy: EnergyType.HIGH_ENERGY,
    radiance: 445,
    timestamp: Date.now() - 6200000,
    reactions: { '🤖': 234, '⚡': 156, '💡': 89 },
    comments: [],
    isBoosted: true,
    userReactions: []
  },
  {
    id: 'post-strategy-session',
    author: MOCK_USERS[4],
    content: "Just wrapped up a 3-hour strategy session with a Fortune 500 company. Their biggest challenge? Not competition—it's internal alignment. When leadership teams aren't synchronized, even the best strategies fail. 🎯\n\nAlignment before acceleration.\n\n#BusinessStrategy #Leadership #Consulting",
    energy: EnergyType.DEEP_DIVE,
    radiance: 298,
    timestamp: Date.now() - 7200000,
    reactions: { '🎯': 167, '💼': 89, '💡': 45 },
    comments: [],
    userReactions: []
  },
  {
    id: 'post-team-psychology',
    author: MOCK_USERS[5],
    content: "Research insight: High-performing teams have 3x more psychological safety than average teams. The cost? Zero. The ROI? Infinite. 🛡️\n\nCreating safe spaces for honest feedback isn't soft—it's strategic.\n\n#TeamDynamics #Leadership #Psychology",
    energy: EnergyType.CALM,
    radiance: 378,
    timestamp: Date.now() - 10800000,
    reactions: { '🧠': 234, '🤝': 156, '💡': 89 },
    comments: [],
    userReactions: []
  },
  {
    id: 'post-fintech-future',
    author: MOCK_USERS[6],
    content: "The future of finance isn't about faster transactions—it's about smarter decisions. We're seeing AI-driven financial planning that's democratizing wealth management. 🏦💡\n\nFinancial literacy + AI = Financial freedom for all.\n\n#FinTech #AI #WealthManagement",
    mediaUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?q=80&w=800&auto=format&fit=crop',
    mediaType: 'image',
    energy: EnergyType.HIGH_ENERGY,
    radiance: 267,
    timestamp: Date.now() - 14400000,
    reactions: { '💰': 189, '🏦': 123, '💡': 67 },
    comments: [],
    userReactions: []
  },
  {
    id: 'post-brand-building',
    author: MOCK_USERS[7],
    content: "Your brand isn't your logo—it's the promise you keep. In an age of infinite choice, consistency is the ultimate differentiator. 🎯\n\nBuilding brands that matter, one promise at a time.\n\n#Branding #Marketing #BusinessGrowth",
    energy: EnergyType.HIGH_ENERGY,
    radiance: 345,
    timestamp: Date.now() - 18000000,
    reactions: { '🎯': 234, '📈': 156, '💼': 89 },
    comments: [],
    userReactions: []
  },
  {
    id: 'post-legal-insights',
    author: MOCK_USERS[8],
    content: "Corporate governance tip: The best contracts prevent disputes before they start. Clear expectations, defined deliverables, and mutual accountability. ⚖️\n\nGood governance is good business.\n\n#CorporateLaw #Governance #Business",
    energy: EnergyType.DEEP_DIVE,
    radiance: 189,
    timestamp: Date.now() - 86400000,
    reactions: { '⚖️': 145, '💼': 89, '💡': 45 },
    comments: [],
    userReactions: []
  },
  {
    id: 'post-talent-development',
    author: MOCK_USERS[9],
    content: "Investing in employee development isn't an expense—it's an investment in your company's future. The ROI? Higher retention, better performance, and a culture that attracts top talent. 🌱\n\nGrow your people, grow your business.\n\n#HR #TalentDevelopment #Leadership",
    energy: EnergyType.CALM,
    radiance: 298,
    timestamp: Date.now() - 95000000,
    reactions: { '🌱': 234, '👥': 167, '💼': 89 },
    comments: [],
    userReactions: []
  },
  {
    id: 'post-manufacturing-innovation',
    author: MOCK_USERS[10],
    content: "Smart manufacturing isn't about replacing humans—it's about augmenting human capability. Our IoT-enabled factory floor has reduced errors by 73% while increasing job satisfaction. 🏭💡\n\nTechnology serves people, not the other way around.\n\n#Manufacturing #IoT #Innovation",
    energy: EnergyType.HIGH_ENERGY,
    radiance: 234,
    timestamp: Date.now() - 172800000,
    reactions: { '🏭': 189, '⚡': 123, '💡': 67 },
    comments: [],
    userReactions: []
  },
  {
    id: 'post-nonprofit-impact',
    author: MOCK_USERS[11],
    content: "Social impact measurement is moving from 'feel good' to 'real impact'. We're now tracking 12 specific metrics across education, healthcare, and economic empowerment. Data-driven compassion. 📊❤️\n\nNumbers tell stories; stories drive change.\n\n#NonProfit #SocialImpact #Leadership",
    energy: EnergyType.DEEP_DIVE,
    radiance: 412,
    timestamp: Date.now() - 200000000,
    reactions: { '❤️': 345, '📊': 234, '🌍': 189 },
    comments: [],
    userReactions: []
  },
  {
    id: 'post-consulting-wisdom',
    author: MOCK_USERS[12],
    content: "20 years of consulting taught me one thing: The smartest solution is rarely the most complex one. Simplicity scales, complexity breaks. 🎯\n\nElegance in execution beats brilliance in theory.\n\n#Consulting #Strategy #Business",
    energy: EnergyType.CALM,
    radiance: 278,
    timestamp: Date.now() - 250000000,
    reactions: { '🎯': 234, '💡': 189, '💼': 123 },
    comments: [],
    userReactions: []
  },
  {
    id: 'post-education-future',
    author: MOCK_USERS[13],
    content: "The future of education isn't online vs. classroom—it's personalized learning paths that adapt to individual needs. We're seeing 40% better outcomes with AI-driven curriculum customization. 🎓🤖\n\nEducation should fit the student, not the other way around.\n\n#Education #AI #FutureOfWork",
    energy: EnergyType.HIGH_ENERGY,
    radiance: 356,
    timestamp: Date.now() - 432000000,
    reactions: { '🎓': 267, '🤖': 189, '💡': 123 },
    comments: [],
    userReactions: []
  },
  {
    id: 'post-startup-reality',
    author: MOCK_USERS[14],
    content: "Startup truth: 80% of success is showing up consistently. The other 20% is having something worth showing up for. Persistence beats perfection every single time. 🚀\n\nBuild in public, fail forward, succeed eventually.\n\n#Startups #Entrepreneurship #Growth",
    energy: EnergyType.HIGH_ENERGY,
    radiance: 423,
    timestamp: Date.now() - 172800000,
    reactions: { '🚀': 345, '💪': 234, '🎯': 189 },
    comments: [],
    userReactions: []
  },
  {
    id: 'post-leadership-morning',
    author: MOCK_USERS[0],
    content: "Morning leadership routine: 30 mins reading industry trends, 15 mins meditation, 10 mins team check-ins, 5 mins setting daily intentions. Start the day with clarity, end it with impact. ☕🎯\n\nHow do you prepare for leadership success?\n\n#Leadership #Productivity #MorningRoutine",
    energy: EnergyType.CALM,
    radiance: 389,
    timestamp: Date.now() - 300000000,
    reactions: { '☕': 234, '🎯': 189, '💡': 123 },
    comments: [],
    userReactions: []
  }
];
