import { AdPackage, Ad, User, EnergyType, CreditBundle, Post } from './types';

export const APP_NAME = "Aura";
export const PRIMARY_COLOR = "emerald-600";

interface CreditBundleData {
  id: string;
  name: string;
  credits: number;
  price: string;
  numericPrice: number;
  description: string;
  gradient: string;
  icon: string;
}

export const CREDIT_BUNDLES: CreditBundleData[] = [
  {
    id: 'bundle-nano-pulse',
    name: 'Nano Pulse',
    credits: 100,
    price: '$9.99',
    numericPrice: 9.99,
    description: 'Perfect for quick post boosts.',
    gradient: 'from-emerald-500 to-teal-500',
    icon: '🔹'
  },
  {
    id: 'bundle-neural-spark',
    name: 'Neural Spark',
    credits: 500,
    price: '$39.99',
    numericPrice: 39.99,
    description: 'Empower your network visibility.',
    gradient: 'from-purple-500 to-indigo-500',
    icon: '✨'
  },
  {
    id: 'bundle-neural-surge',
    name: 'Neural Surge',
    credits: 2000,
    price: '$149.99',
    numericPrice: 149.99,
    description: 'High-frequency growth injection.',
    gradient: 'from-amber-500 to-orange-500',
    icon: '⚡'
  },
  {
    id: 'bundle-universal-core',
    name: 'Universal Core',
    credits: 5000,
    price: '$349.99',
    numericPrice: 349.99,
    description: 'Maximum dominance in the network.',
    gradient: 'from-violet-500 to-purple-500',
    icon: '💎'
  }
];

export const INDUSTRIES = [
  'Technology & Software',
  'Healthcare',
  'Finance',
  'Education',
  'Marketing & Advertising',
  'Manufacturing',
  'Real Estate',
  'Retail',
  'Consulting',
  'Legal Services',
  'Non-Profit',
  'Government',
  'Energy',
  'Transportation',
  'Other'
];

export const COUNTRIES = [
  'United States',
  'United Kingdom',
  'Canada',
  'Australia',
  'Germany',
  'France',
  'Japan',
  'Singapore',
  'India',
  'Brazil',
  'South Africa',
  'Netherlands',
  'Sweden',
  'Other'
];

export const MOCK_USERS: User[] = [
  {
    id: '1',
    firstName: 'James',
    lastName: 'Mitchell',
    name: 'James Mitchell',
    handle: '@jamesmitchell',
    avatar: 'https://picsum.photos/id/64/150/150',
    acquaintances: ['2', '3', '4', '6', '7', '8', '9', '10', '11', '12'],
    email: 'james@leadership.io',
    dob: '1985-03-15',
    blockedUsers: [],
    trustScore: 98,
    auraCredits: 0,
    activeGlow: 'emerald',
    bio: 'CEO at Global Leadership Institute. Author of "The Adaptive Leader". Helping executives navigate complexity.',
    zodiacSign: 'Pisces ♓'
  },
  {
    id: '2',
    firstName: 'Sarah',
    lastName: 'Williams',
    name: 'Sarah Williams',
    handle: '@sarahwilliams',
    avatar: 'https://picsum.photos/id/65/150/150',
    acquaintances: ['1', '3', '5', '9', '11', '13', '14', '15'],
    email: 'sarah@careergrowth.com',
    dob: '1988-07-22',
    blockedUsers: [],
    trustScore: 95,
    auraCredits: 0,
    activeGlow: 'none',
    bio: 'Executive Career Coach. 15+ years helping professionals unlock their potential. TEDx speaker.',
    zodiacSign: 'Cancer ♋'
  },
  {
    id: '3',
    firstName: 'Michael',
    lastName: 'Chen',
    name: 'Michael Chen',
    handle: '@michaelchen',
    avatar: 'https://picsum.photos/id/1012/150/150',
    acquaintances: ['1', '2', '4', '10', '12', '16', '17', '18'],
    email: 'michael@venture.com',
    dob: '1982-11-03',
    blockedUsers: [],
    trustScore: 94,
    auraCredits: 0,
    activeGlow: 'cyan',
    bio: 'Managing Partner at Horizon Ventures. Investing in future of work and sustainable tech.',
    zodiacSign: 'Scorpio ♏'
  },
  {
    id: '4',
    firstName: 'Emily',
    lastName: 'Rodriguez',
    name: 'Emily Rodriguez',
    handle: '@emilyrodriguez',
    avatar: 'https://picsum.photos/id/1027/150/150',
    acquaintances: ['1', '3', '6', '11', '19', '20', '21', '22'],
    email: 'emily@innovationlab.io',
    dob: '1990-01-12',
    blockedUsers: [],
    trustScore: 97,
    auraCredits: 0,
    activeGlow: 'amber',
    bio: 'Founder & CEO of Innovation Labs. Building AI solutions for enterprise transformation.',
    zodiacSign: 'Capricorn ♑'
  },
  {
    id: '5',
    firstName: 'David',
    lastName: 'Thompson',
    name: 'David Thompson',
    handle: '@davidthompson',
    avatar: 'https://picsum.photos/id/1005/150/150',
    acquaintances: ['2', '6', '12', '23', '24', '25', '26'],
    email: 'david@strategy.com',
    dob: '1987-06-30',
    blockedUsers: [],
    trustScore: 91,
    auraCredits: 0,
    activeGlow: 'none',
    bio: 'Business Strategy Consultant. Helping companies scale from startup to enterprise.',
    zodiacSign: 'Cancer ♋'
  },
  {
    id: '6',
    firstName: 'Dr. Lisa',
    lastName: 'Anderson',
    name: 'Dr. Lisa Anderson',
    handle: '@drlisaanderson',
    avatar: 'https://picsum.photos/id/1062/150/150',
    acquaintances: ['1', '4', '5', '13', '27', '28', '29', '30'],
    email: 'lisa@psychology.edu',
    dob: '1983-03-25',
    blockedUsers: [],
    trustScore: 99,
    auraCredits: 0,
    activeGlow: 'emerald',
    bio: 'Organizational Psychologist. Researching leadership effectiveness and team dynamics.',
    zodiacSign: 'Aries ♈'
  },
  {
    id: '7',
    firstName: 'Robert',
    lastName: 'Kim',
    name: 'Robert Kim',
    handle: '@robertkim',
    avatar: 'https://picsum.photos/id/1001/150/150',
    acquaintances: ['1', '8', '14', '31', '32', '33', '34'],
    email: 'robert@fintech.io',
    dob: '1984-02-14',
    blockedUsers: [],
    trustScore: 93,
    auraCredits: 0,
    activeGlow: 'none',
    bio: 'CFO at FinTech Solutions. Expert in financial strategy and business scaling.',
    zodiacSign: 'Aquarius ♒'
  },
  {
    id: '8',
    firstName: 'Jennifer',
    lastName: 'Martinez',
    name: 'Jennifer Martinez',
    handle: '@jennifermartinez',
    avatar: 'https://picsum.photos/id/1003/150/150',
    acquaintances: ['1', '7', '10', '35', '36', '37', '38'],
    email: 'jennifer@marketing.com',
    dob: '1986-09-12',
    blockedUsers: [],
    trustScore: 89,
    auraCredits: 0,
    activeGlow: 'cyan',
    bio: 'CMO at Growth Marketing Agency. Building brands that matter in digital age.',
    zodiacSign: 'Virgo ♍'
  },
  {
    id: '9',
    firstName: 'William',
    lastName: 'Taylor',
    name: 'William Taylor',
    handle: '@williamtaylor',
    avatar: 'https://picsum.photos/id/1025/150/150',
    acquaintances: ['1', '3', '8', '39', '40', '41', '42'],
    email: 'william@legal.com',
    dob: '1981-11-20',
    blockedUsers: [],
    trustScore: 96,
    auraCredits: 0,
    activeGlow: 'none',
    bio: 'Corporate Attorney. Specializing in M&A and corporate governance.',
    zodiacSign: 'Scorpio ♏'
  },
  {
    id: '10',
    firstName: 'Amanda',
    lastName: 'White',
    name: 'Amanda White',
    handle: '@amandawhite',
    avatar: 'https://picsum.photos/id/1005/150/150',
    acquaintances: ['2', '4', '6', '43', '44', '45', '46'],
    email: 'amanda@hr.com',
    dob: '1989-04-15',
    blockedUsers: [],
    trustScore: 92,
    auraCredits: 0,
    activeGlow: 'cyan',
    bio: 'VP of HR at TechCorp. Building inclusive workplaces and talent development programs.',
    zodiacSign: 'Aries ♈'
  },
  {
    id: '11',
    firstName: 'Christopher',
    lastName: 'Brown',
    name: 'Christopher Brown',
    handle: '@christopherbrown',
    avatar: 'https://picsum.photos/id/1006/150/150',
    acquaintances: ['1', '5', '7', '47', '48', '49', '50'],
    email: 'chris@manufacturing.io',
    dob: '1983-08-10',
    blockedUsers: [],
    trustScore: 88,
    auraCredits: 0,
    activeGlow: 'none',
    bio: 'Operations Director at Smart Manufacturing. Optimizing supply chains with IoT.',
    zodiacSign: 'Leo ♌'
  },
  {
    id: '12',
    firstName: 'Michelle',
    lastName: 'Davis',
    name: 'Michelle Davis',
    handle: '@michelledavis',
    avatar: 'https://picsum.photos/id/1007/150/150',
    acquaintances: ['1', '3', '8', '51', '52', '53', '54'],
    email: 'michelle@nonprofit.org',
    dob: '1985-12-05',
    blockedUsers: [],
    trustScore: 94,
    auraCredits: 0,
    activeGlow: 'emerald',
    bio: 'Executive Director at Global Impact Foundation. Leading social change initiatives.',
    zodiacSign: 'Sagittarius ♐'
  },
  {
    id: '13',
    firstName: 'Daniel',
    lastName: 'Miller',
    name: 'Daniel Miller',
    handle: '@danielmiller',
    avatar: 'https://picsum.photos/id/1008/150/150',
    acquaintances: ['2', '6', '9', '55', '56', '57', '58'],
    email: 'daniel@consulting.com',
    dob: '1982-05-18',
    blockedUsers: [],
    trustScore: 90,
    auraCredits: 0,
    activeGlow: 'none',
    bio: 'Senior Consultant at McKinsey. Strategy and transformation expert.',
    zodiacSign: 'Taurus ♉'
  },
  {
    id: '14',
    firstName: 'Jessica',
    lastName: 'Wilson',
    name: 'Jessica Wilson',
    handle: '@jessicawilson',
    avatar: 'https://picsum.photos/id/1009/150/150',
    acquaintances: ['2', '7', '10', '59', '60', '61', '62'],
    email: 'jessica@education.edu',
    dob: '1987-09-25',
    blockedUsers: [],
    trustScore: 95,
    auraCredits: 0,
    activeGlow: 'none',
    bio: 'Dean of Business School. Shaping future business leaders through innovation.',
    zodiacSign: 'Libra ♎'
  },
  {
    id: '15',
    firstName: 'Matthew',
    lastName: 'Moore',
    name: 'Matthew Moore',
    handle: '@matthewmoore',
    avatar: 'https://picsum.photos/id/1010/150/150',
    acquaintances: ['2', '5', '11', '63', '64', '65', '66'],
    email: 'matthew@startup.io',
    dob: '1990-02-28',
    blockedUsers: [],
    trustScore: 87,
    auraCredits: 0,
    activeGlow: 'cyan',
    bio: 'Serial Entrepreneur. 3 exits, currently building future of remote work.',
    zodiacSign: 'Pisces ♓'
  }
];

export const AD_PACKAGES: AdPackage[] = [
  {
    id: 'pkg-leadership-pulse',
    name: 'Leadership Pulse',
    subtitle: 'For executives and business leaders',
    durationDays: 30,
    price: '$299 for 30 Days',
    numericPrice: 299,
    adLimit: 5,
    idealFor: 'For executives and business leaders.',
    features: ['5 Active Ads', '30-Day Duration', 'Priority Feed Placement', 'Executive Network Targeting', 'Advanced Analytics'],
    gradient: 'from-blue-500 to-indigo-600'
  },
  {
    id: 'pkg-career-growth',
    name: 'Career Growth',
    subtitle: 'For career professionals and job seekers',
    durationDays: 30,
    price: '$199 for 30 Days',
    numericPrice: 199,
    adLimit: 3,
    idealFor: 'For career professionals and job seekers.',
    features: ['3 Active Ads', '30-Day Duration', 'Career-Focused Targeting', 'Professional Network Reach', 'Performance Tracking'],
    gradient: 'from-emerald-500 to-teal-600'
  },
  {
    id: 'pkg-business-impact',
    name: 'Business Impact',
    subtitle: 'For business owners and entrepreneurs',
    durationDays: 30,
    price: '$399 for 30 Days',
    numericPrice: 399,
    adLimit: 8,
    idealFor: 'For business owners and entrepreneurs.',
    features: ['8 Active Ads', '30-Day Duration', 'Maximum Network Reach', 'Entrepreneur Targeting', 'Comprehensive Analytics', 'Premium Placement'],
    gradient: 'from-amber-500 to-orange-600'
  }
];

export const INITIAL_ADS: Ad[] = [
  {
    id: 'ad-leadership-summit',
    ownerId: '1',
    ownerName: 'James Mitchell',
    ownerAvatar: 'https://picsum.photos/id/64/150/150',
    headline: 'Global Leadership Summit 2025',
    description: 'Join 500+ executives for premier leadership conference. Keynotes, workshops, and networking.',
    mediaUrl: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?q=80&w=800&auto=format&fit=crop',
    ctaText: 'Register Now',
    ctaLink: '#',
    isSponsored: true,
    placement: 'feed',
    status: 'active',
    subscriptionTier: 'Leadership Pulse',
    reactions: { '🎯': 45, '💼': 28 }
  },
  {
    id: 'ad-career-coaching',
    ownerId: '2',
    ownerName: 'Sarah Williams',
    ownerAvatar: 'https://picsum.photos/id/65/150/150',
    headline: 'Executive Career Transformation',
    description: '1-on-1 coaching to help you reach your next career milestone. Limited spots available.',
    mediaUrl: 'https://images.unsplash.com/photo-1515378791036-0648a3e77b4a?q=80&w=800&auto=format&fit=crop',
    ctaText: 'Book Session',
    ctaLink: '#',
    isSponsored: true,
    placement: 'feed',
    status: 'active',
    subscriptionTier: 'Career Growth',
    reactions: { '🚀': 67, '💡': 34 }
  },
  {
    id: 'ad-venture-fund',
    ownerId: '3',
    ownerName: 'Michael Chen',
    ownerAvatar: 'https://picsum.photos/id/1012/150/150',
    headline: 'Horizon Ventures Fund IV',
    description: 'Now accepting pitches from AI, sustainability, and future of work startups. $100M fund.',
    mediaUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=800&auto=format&fit=crop',
    ctaText: 'Submit Pitch',
    ctaLink: '#',
    isSponsored: true,
    placement: 'feed',
    status: 'active',
    subscriptionTier: 'Business Impact',
    reactions: { '💰': 89, '🚀': 156 }
  },
  {
    id: 'ad-innovation-lab',
    ownerId: '4',
    ownerName: 'Emily Rodriguez',
    ownerAvatar: 'https://picsum.photos/id/1027/150/150',
    headline: 'AI Transformation Workshop',
    description: 'Learn how to implement AI in your enterprise. Hands-on workshop with real-world case studies.',
    mediaUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=800&auto=format&fit=crop',
    ctaText: 'Join Workshop',
    ctaLink: '#',
    isSponsored: true,
    placement: 'feed',
    status: 'active',
    subscriptionTier: 'Leadership Pulse',
    reactions: { '🤖': 78, '⚡': 45 }
  },
  {
    id: 'ad-strategy-consulting',
    ownerId: '5',
    ownerName: 'David Thompson',
    ownerAvatar: 'https://picsum.photos/id/1005/150/150',
    headline: 'Business Scaling Strategy',
    description: 'From startup to enterprise in 12 months. Proven framework for sustainable growth.',
    mediaUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=800&auto=format&fit=crop',
    ctaText: 'Learn More',
    ctaLink: '#',
    isSponsored: true,
    placement: 'feed',
    status: 'active',
    subscriptionTier: 'Business Impact',
    reactions: { '📈': 92, '💼': 67 }
  },
  {
    id: 'ad-leadership-book',
    ownerId: '6',
    ownerName: 'Dr. Lisa Anderson',
    ownerAvatar: 'https://picsum.photos/id/1062/150/150',
    headline: 'The Adaptive Leader - Bestseller',
    description: 'Discover the science behind effective leadership. Now available in audiobook format.',
    mediaUrl: 'https://images.unsplash.com/photo-1531482615713-7afd792de7d1?q=80&w=800&auto=format&fit=crop',
    ctaText: 'Get Book',
    ctaLink: '#',
    isSponsored: true,
    placement: 'feed',
    status: 'active',
    subscriptionTier: 'Career Growth',
    reactions: { '📚': 123, '🧠': 89 }
  }
];

export const CURRENT_USER = MOCK_USERS[0] || {
  id: '',
  firstName: '',
  lastName: '',
  name: '',
  handle: '',
  avatar: '',
  avatarType: 'image' as const,
  acquaintances: [],
  email: '',
  dob: '',
  blockedUsers: [],
  trustScore: 0,
  auraCredits: 0,
  activeGlow: 'none' as const,
  bio: '',
  zodiacSign: ''
};

export const INITIAL_POSTS: Post[] = [
  {
    id: 'post-leadership-vision',
    author: MOCK_USERS[0],
    content: "Strategic leadership requires a balance of vision and execution. The most successful leaders don't just set direction—they create systems that sustain momentum through uncertainty. \n\nWhat's your leadership strategy for driving results in volatile markets?\n\n#Leadership #Strategy #BusinessGrowth",
    energy: EnergyType.DEEP_DIVE,
    radiance: 567,
    timestamp: Date.now() - 1200000,
    reactions: { '🎯': 145, '💡': 89, '🚀': 67 },
    comments: [],
    isBoosted: true,
    userReactions: []
  },
  {
    id: 'post-career-growth',
    author: MOCK_USERS[1],
    content: "Career advancement isn't just about skills—it's about positioning yourself strategically. The professionals who thrive are those who build bridges between departments and anticipate market shifts. \n\nFocus on becoming indispensable, not just qualified.\n\n#CareerDevelopment #ProfessionalGrowth #Leadership",
    mediaUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=800&auto=format&fit=crop',
    mediaType: 'image',
    energy: EnergyType.HIGH_ENERGY,
    radiance: 234,
    timestamp: Date.now() - 3600000,
    reactions: { '🚀': 178, '💼': 89, '🎉': 45 },
    comments: [
      {
        id: 'c1',
        author: MOCK_USERS[0],
        text: "Excellent insight! Strategic positioning is crucial for career progression.",
        timestamp: Date.now() - 1800000,
        reactions: { '🤝': 12 },
        userReactions: []
      }
    ],
    userReactions: ['🚀']
  },
  {
    id: 'post-venture-insights',
    author: MOCK_USERS[2],
    content: "Market analysis reveals: B2B SaaS companies with strong customer success programs grow 3x faster. The future belongs to businesses that prioritize customer outcomes over acquisition. \n\nRetention drives revenue.\n\n#VentureCapital #BusinessStrategy #SaaS",
    energy: EnergyType.CALM,
    radiance: 189,
    timestamp: Date.now() - 5400000,
    reactions: { '💰': 156, '🚀': 89, '💡': 67 },
    comments: [],
    userReactions: []
  },
  {
    id: 'post-innovation-daily',
    author: MOCK_USERS[3],
    content: "Digital transformation success story: Implemented AI-driven customer service that reduced response time by 80% while increasing satisfaction scores. The key? Human-centered design with machine efficiency. \n\nInnovation that matters solves real problems.\n\n#AI #DigitalTransformation #CustomerExperience",
    mediaUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=800&auto=format&fit=crop',
    mediaType: 'image',
    energy: EnergyType.HIGH_ENERGY,
    radiance: 445,
    timestamp: Date.now() - 6200000,
    reactions: { '🤖': 234, '⚡': 156, '💡': 89 },
    comments: [],
    isBoosted: true,
    userReactions: []
  },
  {
    id: 'post-strategy-session',
    author: MOCK_USERS[4],
    content: "Just concluded a board strategy retreat for a healthcare company. Their transformation roadmap: 1) Patient data analytics, 2) Telemedicine integration, 3) Outcome-based pricing. The future of healthcare is predictive, not reactive. \n\nValue-based care is the next frontier.\n\n#HealthcareStrategy #Innovation #BusinessGrowth",
    energy: EnergyType.DEEP_DIVE,
    radiance: 298,
    timestamp: Date.now() - 7200000,
    reactions: { '🎯': 167, '💼': 89, '💡': 45 },
    comments: [],
    userReactions: []
  },
  {
    id: 'post-team-psychology',
    author: MOCK_USERS[5],
    content: "Research breakthrough: Teams with diverse cognitive styles outperform homogeneous groups by 42% on complex problem-solving. The secret ingredient? Psychological safety and structured dissent. \n\nCognitive diversity drives innovation.\n\n#TeamDynamics #Leadership #Psychology",
    energy: EnergyType.CALM,
    radiance: 378,
    timestamp: Date.now() - 10800000,
    reactions: { '🧠': 234, '🤝': 156, '💡': 89 },
    comments: [],
    userReactions: []
  },
  {
    id: 'post-fintech-future',
    author: MOCK_USERS[6],
    content: "The next wave in fintech: Embedded finance solutions that integrate seamlessly into non-financial platforms. We're seeing B2B commerce platforms offering lending, insurance companies providing investment tools. \n\nFinance becomes invisible infrastructure.\n\n#FinTech #EmbeddedFinance #Innovation",
    mediaUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?q=80&w=800&auto=format&fit=crop',
    mediaType: 'image',
    energy: EnergyType.HIGH_ENERGY,
    radiance: 267,
    timestamp: Date.now() - 14400000,
    reactions: { '💰': 189, '🏦': 123, '💡': 67 },
    comments: [],
    userReactions: []
  },
  {
    id: 'post-brand-building',
    author: MOCK_USERS[7],
    content: "Brand differentiation in saturated markets requires authentic purpose. Consumers connect with values, not features. The strongest brands tell stories that align with customer identities. \n\nPurpose drives loyalty.\n\n#BrandStrategy #Marketing #CustomerEngagement",
    energy: EnergyType.HIGH_ENERGY,
    radiance: 345,
    timestamp: Date.now() - 18000000,
    reactions: { '🎯': 234, '📈': 156, '💼': 89 },
    comments: [],
    userReactions: []
  },
  {
    id: 'post-legal-insights',
    author: MOCK_USERS[8],
    content: "Regulatory compliance strategy: Proactive adaptation versus reactive compliance saves 60% in legal costs. Forward-thinking companies embed regulatory intelligence into product development cycles. \n\nCompliance as competitive advantage.\n\n#CorporateLaw #Compliance #RiskManagement",
    energy: EnergyType.DEEP_DIVE,
    radiance: 189,
    timestamp: Date.now() - 86400000,
    reactions: { '⚖️': 145, '💼': 89, '💡': 45 },
    comments: [],
    userReactions: []
  },
  {
    id: 'post-talent-development',
    author: MOCK_USERS[9],
    content: "Internal mobility programs increase retention by 70% and reduce hiring costs. The best companies develop talent pipelines that anticipate future skill needs. \n\nGrow your people, secure your future.\n\n#HRStrategy #TalentDevelopment #EmployeeEngagement",
    energy: EnergyType.CALM,
    radiance: 298,
    timestamp: Date.now() - 95000000,
    reactions: { '🌱': 234, '👥': 167, '💼': 89 },
    comments: [],
    userReactions: []
  },
  {
    id: 'post-manufacturing-innovation',
    author: MOCK_USERS[10],
    content: "Industry 4.0 implementation: Our smart factory achieved 35% efficiency gains through predictive maintenance and real-time quality monitoring. The ROI came in 18 months instead of the projected 3 years. \n\nSmart manufacturing drives profitability.\n\n#Manufacturing #Industry40 #OperationalExcellence",
    energy: EnergyType.HIGH_ENERGY,
    radiance: 234,
    timestamp: Date.now() - 172800000,
    reactions: { '🏭': 189, '⚡': 123, '💡': 67 },
    comments: [],
    userReactions: []
  },
  {
    id: 'post-nonprofit-impact',
    author: MOCK_USERS[11],
    content: "Measurable social impact: Our education initiative reached 10,000 students with 89% improvement in standardized test scores. Evidence-based philanthropy creates sustainable community transformation. \n\nData drives meaningful change.\n\n#SocialImpact #Education #Philanthropy",
    energy: EnergyType.DEEP_DIVE,
    radiance: 412,
    timestamp: Date.now() - 200000000,
    reactions: { '❤️': 345, '📊': 234, '🌍': 189 },
    comments: [],
    userReactions: []
  },
  {
    id: 'post-consulting-wisdom',
    author: MOCK_USERS[12],
    content: "25 years in strategy consulting revealed: The most successful transformations begin with culture, not process. Technical changes succeed when aligned with human motivations. \n\nPeople execute strategy.\n\n#ChangeManagement #Leadership #Strategy",
    energy: EnergyType.CALM,
    radiance: 278,
    timestamp: Date.now() - 250000000,
    reactions: { '🎯': 234, '💡': 189, '💼': 123 },
    comments: [],
    userReactions: []
  },
  {
    id: 'post-education-future',
    author: MOCK_USERS[13],
    content: "Skills-based hiring is transforming recruitment: 75% of talent leaders report better performance from skills-focused candidates versus degree-focused ones. The future rewards competency over credentials. \n\nSkills matter more than pedigree.\n\n#Recruitment #SkillsBasedHiring #TalentStrategy",
    energy: EnergyType.HIGH_ENERGY,
    radiance: 356,
    timestamp: Date.now() - 432000000,
    reactions: { '🎓': 267, '🤖': 189, '💡': 123 },
    comments: [],
    userReactions: []
  },
  {
    id: 'post-startup-reality',
    author: MOCK_USERS[14],
    content: "Series A insights: Companies with unit economics clarity raise 40% faster and achieve 60% higher valuations. Investors reward businesses that understand profitability drivers early. \n\nUnit economics drives investor confidence.\n\n#Startups #Fundraising #UnitEconomics",
    energy: EnergyType.HIGH_ENERGY,
    radiance: 423,
    timestamp: Date.now() - 172800000,
    reactions: { '🚀': 345, '💪': 234, '🎯': 189 },
    comments: [],
    userReactions: []
  }
];
